### ISSUE TITLE
zsh: command not found: mongod

### ISSUE THREAD

**Issue by rhnkyr** [JamesKovacs/zsh_completions_mongodb#8]
Hi there,

I setup  the files according to your doc and even tried the antigen. Before oh-my-zsh mongod worked properly. What did I do wrong?

**Comment by stennie** [comment]
@rhnkyr The error `command not found: mongod` suggests the `mongod` binary isn't in your path. I expect this is unrelated to zsh completions.

Were you able to resolve your issue?

Regards,
Stennie
